services:
  redis:
    image: redis
    ports:
      - '6379:6379'
    restart: always

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
